name: movie_browser_app
description: "A Flutter movie browser app for Tugas Besar Pemrograman Mobile"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  provider: ^6.0.0
  shared_preferences: ^2.0.0
  cached_network_image: ^3.0.0
  shimmer: ^3.0.0
  youtube_player_flutter: ^9.1.0
  badges: ^3.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_inappwebview: ^6.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo-apps.png"
  adaptive_icon_foreground: "assets/images/logo-apps.png"
